name: Tic Tac Toe CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server_ci:
    name: Server CI 
    runs-on: ubuntu-latest
    container: python:3-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: server
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run tests
        working-directory: server/tests
        run: |
          python -m unittest test_game
          python -m twisted.trial test_server 

