name: Tic Tac Toe CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server_ci:
    name: Server CI 
    runs-on: ubuntu-latest
    container: python:3-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r server/requirements.txt

      - name: Run tests
        run: |
          python -m unittest server/tests/test_game
          python -m twisted.trial server/tests/test_server 

