name: Tic Tac Toe CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server_ci:
    name: Server CI 
    runs-on: ubuntu-latest
    container: python:3-slim
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest tests/test_game.py
          python -m twisted.trial tests/test_server.py 

