name: Tic Tac Toe CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  server_job:
    name: Server CI job

    build:
      runs-on: ubuntu-latest
      container: python:3-slim

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install dependencies
          run: |
            cd server
            python -m pip install --upgrade pip wheel
            pip install -r requirements.txt

        - name: Run tests 
          run: |
            cd tests
            ./run_tests.sh
